-- MySQL Script generated by MySQL Workbench
-- 11/23/17 02:58:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tms_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tms_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tms_db` DEFAULT CHARACTER SET utf8 ;
USE `tms_db` ;

-- -----------------------------------------------------
-- Table `tms_db`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms_db`.`project` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `active_status` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tms_db`.`checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms_db`.`checklist` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fk_project_id` INT(10) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `active_status` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_project_id_idx` (`fk_project_id` ASC),
  INDEX `_idx` (`fk_project_id` ASC),
  CONSTRAINT `fk_project_id`
    FOREIGN KEY (`fk_project_id`)
    REFERENCES `tms_db`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tms_db`.`level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms_db`.`level` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tms_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms_db`.`role` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tms_db`.`run_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms_db`.`run_status` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tms_db`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms_db`.`type` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tms_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms_db`.`user` (
  `id` INT(10) NOT NULL,
  `fk_role_id` INT(10) NOT NULL,
  `principal_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `principal_name_UNIQUE` (`principal_name` ASC),
  INDEX `_idx` (`fk_role_id` ASC),
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`fk_role_id`)
    REFERENCES `tms_db`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tms_db`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms_db`.`test` (
  `id` INT(10) NOT NULL,
  `fk_checklist_id` INT(10) NOT NULL,
  `fk_user_id` INT(10) NOT NULL,
  `fk_type_id` INT(10) NULL DEFAULT NULL,
  `fk_level_id` INT(10) NULL DEFAULT NULL,
  `fk_run_status` INT(10) NULL DEFAULT NULL,
  `title` VARCHAR(1000) NOT NULL,
  `description` LONGBLOB NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `file_name` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_checklist_id_idx` (`fk_checklist_id` ASC),
  INDEX `fk_type_id_idx` (`fk_type_id` ASC),
  INDEX `fk_user_id_idx` (`fk_user_id` ASC),
  INDEX `fk_level_id_idx` (`fk_level_id` ASC),
  INDEX `fk_run_status_id_idx` (`fk_run_status` ASC),
  CONSTRAINT `fk_checklist_id`
    FOREIGN KEY (`fk_checklist_id`)
    REFERENCES `tms_db`.`checklist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_level_id`
    FOREIGN KEY (`fk_level_id`)
    REFERENCES `tms_db`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_run_status_id`
    FOREIGN KEY (`fk_run_status`)
    REFERENCES `tms_db`.`run_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_type_id`
    FOREIGN KEY (`fk_type_id`)
    REFERENCES `tms_db`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `tms_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
